### ISSUE TITLE
Jewel plugin (for Julia) loaded multiple times

### ISSUE THREAD

**Issue by vuilehaid** [joshuafcole/recall#18]
Using the Jewel plugin (for programming Julia) in combination with the Recall plugin, results in multiple instances of the Julia connection after opening and closing Light Table several times.

![image](https://cloud.githubusercontent.com/assets/4154369/3209083/602aebda-ee58-11e3-925d-e137287ebc45.png)

**Comment by joshuafcole** [comment]
This is very interesting. With Recall removed. does the Julia plugin
automatically attempt to reopen files? Alternatively, does it automatically
spin up a client when a julia file is opened? All Recall does is execute
the open-file lt command on the files that were last open and move the
cursor to the appropriate location in that editor. I'd bank on this being
an issue with the Jewel plugin, but I'm not sure what behavior would cause
that result.

On Sat, Jun 7, 2014 at 8:29 AM, vuilehaid notifications@github.com wrote:

> Using the Jewel plugin (for programming Julia) in combination with the
> Recall plugin, results in multiple instances of the Julia connection after
> opening and closing Light Table several times.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/4154369/3209083/602aebda-ee58-11e3-925d-e137287ebc45.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joshuafcole/recall/issues/18.

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by vuilehaid** [comment]
With the Recall plugin disabled: when starting Light Table, a Julia client is spun up automatically, without having to open a file first. 

I did the following test: I manually opened, very quickly after starting Light Table, some Julia files. This also results in multiple Julia clients. 

From this, I conclude that this is a issue with the Jewel plugin: when files are opened before the Julia client is fully loaded, it will create a new Julia client instance.

**Comment by joshuafcole** [comment]
makes sense, if there is anything else I can help with, don't hesitate to
let me know.

On Sat, Jun 7, 2014 at 2:28 PM, vuilehaid notifications@github.com wrote:

> With the Recall plugin disabled: when starting Light Table, a Julia client
> is spun up automatically, without having to open a file first.
> 
> I did the following test: I manually opened, very quickly after starting
> Light Table, some Julia files. This also results in multiple Julia clients.
> 
> From this, I conclude that this is a issue with the Jewel plugin: when
> files are opened before the Julia client is fully loaded, it will create a
> new Julia client instance.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joshuafcole/recall/issues/18#issuecomment-45421701.

## 

Screw the environment. Please print this email immediately. And then burn
it.
