### ISSUE TITLE
Error when LT loads

### ISSUE THREAD

**Issue by jeluard** [joshuafcole/recall#7]
After installing `recall` 0.0.2 via plugin manager I get following exception in the console:

``` javascript
Error: Cannot find module '/Users/julien/Library/Application Support/LightTable/plugins/recall/node_modules/ltrap' 
at Function.Module._resolveFilename (module.js:341:15) 
at Function.Module._load (module.js:280:25) 
at Module.require (module.js:367:17) 
at require (module.js:383:17) 
at window.require (eval at undefined, <anonymous>:1:112) 
at recallBootstrap (eval at <anonymous> (app://lighttable/core/node_modules/lighttable/bootstrap.js), <anonymous>:12:15) 
at eval (eval at <anonymous> (app://lighttable/core/node_modules/lighttable/bootstrap.js), <anonymous>:100:3) 
at eval (native) at c (app://lighttable/core/node_modules/lighttable/bootstrap.js:21207:41) 
at a (app://lighttable/core/node_modules/lighttable/bootstrap.js:21215:18)
bootstrap.js [28176]    lt.objs.plugins.__BEH__load_js
```

Nothing is restored then.

**Comment by joshuafcole** [comment]
Sorry Julien, you'll need to manually run "npm i" in the recall plugin
directory. That rule of thumb currently goes for all of my plugins (and any
other node plugins that don't figure out how to pull in deps
automatically). There isn't currently a good way to set up a postinstall
hook. I'm going to look into setting something up for that purpose, but I'm
presently working with Chris to find a good solution to a serious issue
with providing custom themes and skins.

On Thu, Jan 9, 2014 at 6:28 PM, Julien Eluard notifications@github.comwrote:

> After installing recall 0.0.2 via plugin manager I get following
> exception in the console:
> 
> Error: Cannot find module '/Users/julien/Library/Application Support/LightTable/plugins/recall/node_modules/ltrap' at Function.Module._resolveFilename (module.js:341:15) at Function.Module._load (module.js:280:25) at Module.require (module.js:367:17) at require (module.js:383:17) at window.require (eval at undefined, <anonymous>:1:112) at recallBootstrap (eval at <anonymous> (app://lighttable/core/node_modules/lighttable/bootstrap.js), <anonymous>:12:15) at eval (eval at <anonymous> (app://lighttable/core/node_modules/lighttable/bootstrap.js), <anonymous>:100:3) at eval (native) at c (app://lighttable/core/node_modules/lighttable/bootstrap.js:21207:41) at a (app://lighttable/core/node_modules/lighttable/bootstrap.js:21215:18)bootstrap.js [28176]    lt.objs.plugins.__BEH__load_js
> 
> Nothing is restored then.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/recall/issues/7
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by jeluard** [comment]
Ah I didn't know that! Works perfect now.
Thanks for creating this plugin!
